# Generated by Django 5.2.7 on 2025-10-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('top3', models.JSONField(default=list)),
                ('national_percentages', models.JSONField(default=dict)),
                ('participation', models.FloatField(blank=True, null=True)),
                ('margin_1_2', models.FloatField(blank=True, null=True)),
                ('blanco_nulo_impugnado', models.FloatField(blank=True, null=True)),
                ('provinciales', models.JSONField(default=dict)),
                ('bonus', models.JSONField(default=dict)),
                ('sync_pending', models.BooleanField(default=False)),
            ],
        ),
    ]
