# Generated by Django 5.2.7 on 2025-10-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_prediction_total_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('national_percentages', models.JSONField(default=dict)),
                ('participation', models.FloatField(blank=True, null=True)),
                ('margin_1_2', models.FloatField(blank=True, null=True)),
                ('blanco_nulo_impugnado', models.FloatField(blank=True, null=True)),
                ('total_votes', models.BigIntegerField(blank=True, null=True)),
                ('provinciales', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
